config/routes.rb
Rails.application.routes.draw do

  resources :carts, only: :show
  devise_for :users
  get 'dashboard/index'

  resources :products do
    resources :orders, only: :create
  end

  root 'products#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  has_many :orders

  before_save :update_total_price
  after_save :create_new_cart
  has_one :payment


  def update_total_price
    self.total_price = current_price
  end

  def create_new_cart
    if self == user.last_cart and not(self.open?)
      self.user.carts.build().save
    end
  end

  def close!
    self.open = false
    save
  end

  def current_price
    orders.collect(&:price).sum()
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :cart
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :cart

  after_create :close_cart

  def close_cart
    self.cart.close!
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :store
  has_many :orders
  has_many :users, through: :orders
  validates :price, presence: true

end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  has_many :products
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :products, through: :orders
  has_many :carts
  has_one :last_cart, ->{ order 'created_at desc'}, class_name: 'Cart'

  after_create :build_cart

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def build_cart
    new_cart = carts.build(total_price:0, open:true)
    new_cart.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_user.last_cart
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @categories = Category.joins(:products).group(:category_id, "categories.name").pluck("categories.name, count(products.category_id)")
    @products_by_day = Product.group_by_day(:created_at).count
    @products_by_order = Product.includes(:orders).group(:name, :product_id).pluck("products.name", "count(orders.id)")
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    current_user.last_cart.orders << Order.new(user:current_user, price: @product.price, product: @product)

    if current_user.last_cart.save
      redirect_to products_path, notice: "La orden ha sido guardada"
    else
      redirect_to products_path, alert: "La orden no ha podido ser guardada"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @stores = Store.near([current_user.latitude, current_user.longitude], 2, :units => :km)
    @products = Product.where(store_id: @stores.collect(&:id))

    @markers = Gmaps4rails.build_markers(@stores) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :stock, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<div class="col-md-6 col-md-offset-3"> 
	<table class="table">
		<thead> 
			<tr>
				<td>Producto</td>
				<td>Precio</td>
				<td>Seleccionado hace:</td>
			</tr>
		</thead>
		<tbody>
			<% @cart.orders.each do |order| %>
			<tr>
				<td> <%= order.product.name %> </td>
				<td> <%= order.product.price %> </td>
				<td> <%= time_ago_in_words(order.created_at) %> </td>
			</tr>
			<% end %>
			<tr class="success">
				<td>  </td>
				<td> Total: <%= @cart.total_price%></td>
				<td> <a href="#" class="btn btn-primary"> Comprar </a> </td>
			</tr>
		</tbody>
	</table>
</div>

app/views/dashboard/index.html.erb
<h1> Panel de control </h1>

<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<div class="row">
	<div class="col-md-6">
		<div class="well">
			<h3> Productos por categoría </h3>
			<%= pie_chart @categories %>
		</div>
	</div>

	<div class="col-md-6">
		<div class="well">
			<h3> Productos creados por día </h3>
			<%= line_chart @products_by_day %>
		</div>
	</div>

</div>

<div class="row">
	<div class="col-md-6">
		<div class="well">
			<h3> Productos más vendidos </h3>
			<%= column_chart @products_by_order %>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>

        <li><%= link_to "Panel de control", dashboard_index_path %></a></li>

        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to "Carro (#{current_user.last_cart.orders.count})", current_user.last_cart %> </a> </li>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete">Log out</a></li>
        <% else %>
          <li><a href="<%= new_user_session_path %>">Log in</a></li>
          <li><a href="<%= new_user_registration_path %>">Sign up</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <title>Graficos</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :stock %>
    <%= f.number_field :stock %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.text_field :category_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <h1>Products</h1>
    <table>
      <tbody>
        <% @products.each do |product| %>
        <div class="col-md-6">
          <div class="well">
            <h4> <%= product.name %> <small> (<%= product.category.try(:name) %>) </small></h4>
            <h5> tienda: <%= product.store.name %> </h5>
            <p> Precio: <%= product.price %> </p>
            <p> Stock: <%= product.stock %> </p>
            <%= link_to 'Comprar', product_orders_path(product), method: :post, class:"btn btn-primary" %>
          </div>
        </div>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Product', new_product_path %>
  </div>
  <div class="col-md-6">
    <div id="map" style='width: 100%; height: 300px;'></div>
  </div>
</div>

<script>
  function initMap(){
    handler = Gmaps.build('Google');
    handler.buildMap({
      provider: {
        zoom: 13,
        center: {lat:<%= current_user.latitude %>, lng:<%= current_user.longitude%>},
      },
      internal: {id: 'map'}
    }, function(){
      markers = handler.addMarkers(<%=raw @markers.to_json %>);
      map = handler.getMap();
      new google.maps.Circle({
        map: map,
        center: {lat:<%= current_user.latitude %>, lng:<%= current_user.longitude %>},
        radius: 2000,
        fillColor: '#FF0000',
        strokeColor: '#FF0000'
      });

      // google.maps.event.addListener(map, "click", function(){
      //   console.log("hola");
      // });

    });
  };
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2uIfbiVh5I0nUc51Yy3yWh9FSc3eK9I8&callback=initMap"
async defer></script>

<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>